export const muro1 = [
  { 
   id: 1,
    title: "Andrew Boston añadió un nuevo elemento a su perfil",
    fotopersonal: "./assets/fotoprinc.png",
    redsocial: "@andrewboston",
    image: "./assets/link2.png",    
    txtlinl: "Link",
    imgframe: "./assets/frame.png",
    time: "hace 2 horas",
    titulosub1: "Título del Elemento",
    subtitulo: "Lorem ipsum dolor sit amet consectetur. Faucibus maecenas",
   },
  {
    id: 2,
    title: "Andrew Boston añadió un nuevo elemento a su perfil",
    fotopersonal: "./assets/fotoprinc.png",
    redsocial: "@andrewboston",
    image: "./assets/nube.png",  
    txtlinl: "Archivo",
    imgframe: "./assets/frame.png",
    time: "hace 2 horas",
    titulosub1: "Título del Elemento",
    subtitulo: "Lorem ipsum dolor sit amet consectetur. Faucibus maecenas",
  },
  {
    id: 3,
    title: "Andrew Boston añadió un nuevo elemento a su perfil",
    fotopersonal: "./assets/fotoprinc.png",
    redsocial: "@andrewboston",
    image: "./assets/imgfoto.png",   
    txtlinl: "Imagen",
    imgframe: "./assets/frame.png",
    time: "hace 2 horas",
    titulosub1: "Título del Elemento",
    subtitulo: "Lorem ipsum dolor sit amet consectetur. Faucibus maecenas",
  },
  {
    id: 4,
    title: "Andrew Boston añadió un nuevo elemento a su perfil",
    fotopersonal: "./assets/fotoprinc.png",
    redsocial: "@andrewboston",
    image: "./assets/instagramred.png",    
    txtlinl: "Instagram",
    imgframe: "./assets/frameinsta.png",
    time: "hace 2 horas",
    titulosub1: "Título del Elemento",
    subtitulo: "Lorem ipsum dolor sit amet consectetur. Faucibus maecenas",    
    imginsta: "./assets/icon-like.png",
    comentsinsta: "./assets/comment.png",
    instacount: "100",
    instacomen: "100",
  },
  {
    id: 5,
    title: "Andrew Boston añadió un nuevo elemento a su perfil",
    fotopersonal: "./assets/fotoprinc.png",
    redsocial: "@andrewboston",
    image: "./assets/instagramred.png",    
    txtlinl: "Instagram",
    imgframe: "./assets/frameinsta.png",
    time: "hace 2 horas",
    titulosub1: "Título del Elemento",
    subtitulo: "Lorem ipsum dolor sit amet consectetur. Faucibus maecenas",    
    imginsta: "./assets/icon-like.png",
    comentsinsta: "./assets/comment.png",
    barraslices: "./assets/barraslices.png",
    instacount: "100",
    instacomen: "100",
  },
  {
    id: 6,
    title: "Andrew Boston añadió un nuevo elemento a su perfil",
    fotopersonal: "./assets/fotoprinc.png",
    redsocial: "@andrewboston",
    image: "./assets/image-video.png",    
    txtlinl: "Video",
    imgframe: "./assets/barravideo.png",
    time: "hace 2 horas",
    titulosub1: "Título del Elemento",
    subtitulo: "Lorem ipsum dolor sit amet consectetur. Faucibus maecenas",    
    imginsta: "./assets/icon-like.png",
    comentsinsta: "./assets/comment.png",
    barraslices: "./assets/barraslices.png",
    instacount: "100",
    instacomen: "100",
  },
  {
    id: 7,
    title: "Andrew Boston añadió un nuevo elemento a su perfil",
    fotopersonal: "./assets/fotoprinc.png",
    redsocial: "@andrewboston",
    image: "./assets/icoyoutube.png",    
    txtlinl: "Youtube",
    imgframe: "./assets/frameyoutube.png",
    time: "hace 2 horas",
    titulosub1: "Título del Elemento",
    subtitulo: "Lorem ipsum dolor sit amet consectetur. Faucibus maecenas",    
    imginsta: "./assets/icon-like.png",
    comentsinsta: "./assets/comment.png",
    barraslices: "./assets/barraslices.png",
    instacount: "100",
    instacomen: "100",
  },  
  


 
];
