export const userslistdos = [
    {
      id: 1,
      title: "Bowen Group",
      subtitle: "@BowenGroup",
      image: "assets/avatars/Avatar.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
      
    },
    {
      id: 2,
      title: "Alex Hamilton",
      subtitle: "@AlexHamilton",
      image: "./assets/avatars/Avatar2.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },
    {
      id: 3,
      title: "Taylor Smith",
      subtitle: "@TaylorSmith",
      image: "./assets/avatars/Avatar3.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },
    {
      id: 4,
      title: "Darcy Patterson",
      subtitle: "@DarcyPatterson",
      image: "./assets/avatars/Avatar4.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },
    {
      id: 5,
      title: "21 Industries",
      subtitle: "@21Industries",
      image: "./assets/avatars/Avatar5.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },
    {
      id: 6,
      title: "Bowen Group",
      subtitle: "@AlexHamilton",
      image: "./assets/avatars/Avatar6.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },
    {
      id: 7,
      title: "Alex Hamilton",
      subtitle: "@TaylorSmith",
      image: "./assets/avatars/Avatar7.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },
    {
      id: 8,
      title: "Taylor Smith",
      subtitle: "@TaylorSmith",
      image: "./assets/avatars/Avatar8.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },
    {
      id: 9,
      title: "Darcy Patterson",
      subtitle: "@DarcyPatterson",
      image: "./assets/avatars/Avatar9.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },
  ];