export const userslisttres = [
    {
      id: 1,
      title: "Andrew Boston",
      subtitle: "@andrewboston",
      image: "assets/avatars/mujerfoto.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
      
    },
    {
      id: 2,
      title: "Taylor Smith",
      subtitle: "@taylorsmith",
      image: "./assets/avatars/avatafotr.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },
    {
      id: 3,
      title: "Selma Knight",
      subtitle: "@selma_k",
      image: "./assets/avatars/avatarfot2.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },
    {
      id: 4,
      title: "Mary Cruz",
      subtitle: "@marcruz_ok",
      image: "./assets/avatars/mujerfoto3.png",
      image2: "./assets/verify.png",
      siguiendo: "./assets/user-checkmor.png",
      seguir: "./assets/user-plusseg.png",
      txtsiguiendo: "Siguiendo",
      txtseguir: "Seguir",
    },    
  ];